### ISSUE TITLE
Images take up lots of space

### ISSUE THREAD

**Issue by jacobparish** [investingwolf/react-native-svg-path-gradient#10]
I don't really want to have these gifs in my node_modules folder. NPM says 194 kb unpacked size, when this lib should be a few kb at most.

Options we have:
- keep it as is
- add images to .npmignore (will this make them not show up on the npm package page?)
- host images outside of the repo and link the url in the readme

**Comment by Mkassabov** [comment]
@jacobparish this is great input. I have opened a [PR#11](https://github.com/investingwolf/react-native-svg-path-gradient/pull/11) addressing this exact issue, and moving the images to be hosted on imgur.
